<?xml version="1.0" encoding="utf-8"?><Database Name="bazaQuiz" Class="bazaQuizDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\v11.0;AttachDbFilename=|DataDirectory|\bazaQuiz.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="Quiz.Properties.Settings" SettingsPropertyName="bazaQuizConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Gra" Member="Gras">
    <Type Name="Gra">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="data_rozgrywki" Type="System.DateTime" DbType="Date NOT NULL" CanBeNull="false" />
      <Column Name="id_uzytkownika" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Gra_Zadane_Pytania" Member="Zadane_Pytanias" ThisKey="Id" OtherKey="id_gra" Type="Zadane_Pytania" />
      <Association Name="Uzytkownicy_Gra" Member="Uzytkownicy" ThisKey="id_uzytkownika" OtherKey="Id" Type="Uzytkownicy" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Zadane_Pytania" Member="Zadane_Pytanias">
    <Type Name="Zadane_Pytania">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_gra" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_pytania" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Zadane_Pytania_Udzielona_odpowiedz" Member="Udzielona_odpowiedzs" ThisKey="Id" OtherKey="id_zadane_pytanie" Type="Udzielona_odpowiedz" />
      <Association Name="Gra_Zadane_Pytania" Member="Gra" ThisKey="id_gra" OtherKey="Id" Type="Gra" IsForeignKey="true" />
      <Association Name="Pytania_Zadane_Pytania" Member="Pytania" ThisKey="id_pytania" OtherKey="Id" Type="Pytania" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Kategoria" Member="Kategorias">
    <Type Name="Kategoria">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="nazwa" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Association Name="Kategoria_Pytania" Member="Pytanias" ThisKey="Id" OtherKey="id_kategoria" Type="Pytania" />
    </Type>
  </Table>
  <Table Name="dbo.Odpowiedzi" Member="Odpowiedzis">
    <Type Name="Odpowiedzi">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_pytania" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="odp" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="czy_poprawna" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Odpowiedzi_Udzielona_odpowiedz" Member="Udzielona_odpowiedzs" ThisKey="Id" OtherKey="id_odpowiedzi" Type="Udzielona_odpowiedz" />
      <Association Name="Pytania_Odpowiedzi" Member="Pytania" ThisKey="id_pytania" OtherKey="Id" Type="Pytania" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Pytania" Member="Pytanias">
    <Type Name="Pytania">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_typ" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="tresc" Type="System.String" DbType="VarChar(500) NOT NULL" CanBeNull="false" />
      <Column Name="id_kategoria" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Pytania_Zadane_Pytania" Member="Zadane_Pytanias" ThisKey="Id" OtherKey="id_pytania" Type="Zadane_Pytania" />
      <Association Name="Pytania_Odpowiedzi" Member="Odpowiedzis" ThisKey="Id" OtherKey="id_pytania" Type="Odpowiedzi" />
      <Association Name="Kategoria_Pytania" Member="Kategoria" ThisKey="id_kategoria" OtherKey="Id" Type="Kategoria" IsForeignKey="true" />
      <Association Name="Typ_pytania_Pytania" Member="Typ_pytania" ThisKey="id_typ" OtherKey="Id" Type="Typ_pytania" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Typ_pytania" Member="Typ_pytanias">
    <Type Name="Typ_pytania">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="poziom" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Typ_pytania_Pytania" Member="Pytanias" ThisKey="Id" OtherKey="id_typ" Type="Pytania" />
    </Type>
  </Table>
  <Table Name="dbo.Udzielona_odpowiedz" Member="Udzielona_odpowiedzs">
    <Type Name="Udzielona_odpowiedz">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="id_odpowiedzi" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Column Name="id_zadane_pytanie" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
      <Association Name="Odpowiedzi_Udzielona_odpowiedz" Member="Odpowiedzi" ThisKey="id_odpowiedzi" OtherKey="Id" Type="Odpowiedzi" IsForeignKey="true" />
      <Association Name="Zadane_Pytania_Udzielona_odpowiedz" Member="Zadane_Pytania" ThisKey="id_zadane_pytanie" OtherKey="Id" Type="Zadane_Pytania" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Uzytkownicy" Member="Uzytkownicies">
    <Type Name="Uzytkownicy">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="user_name" Type="System.String" DbType="VarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="password" Type="System.String" DbType="NVarChar(50) NOT NULL" CanBeNull="false" />
      <Column Name="czy_admin" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Association Name="Uzytkownicy_Gra" Member="Gras" ThisKey="Id" OtherKey="id_uzytkownika" Type="Gra" />
    </Type>
  </Table>
</Database>